#!/usr/bin/env bash

DOT_PATH="$(realpath $0 | xargs dirname)"

if ! pacman -Qi oils-for-unix > /dev/null; then
  OILS_AUR_PATH="$(mktemp -d)"
  git clone https://aur.archlinux.org/oils-for-unix.git $OILS_AUR_PATH
  # BUG: to disable debug package we have to have makepkg.conf prepared
  cd $OILS_AUR_PATH && makepkg -si --noconfirm
else
  echo 'oils-for-unix is already installed.'
fi

$DOT_PATH/dotsync
