#!/usr/bin/env sh

if which bb; then
    echo "babashka already installed, skipping installation"
else
    echo "installing babashka..."
    mkdir -p /tmp/dotfiles
    curl -o /tmp/dotfiles/installbb https://raw.githubusercontent.com/babashka/babashka/master/install
    chmod +x /tmp/dotfiles/installbb
    sudo /tmp/dotfiles/installbb --dir /usr/bin
fi

./dotman
