-- -- Function to get the Merlin share path
-- local function get_merlin_share_path()
--   -- Find the path of `ocamlmerlin` using `vim.fn.exepath()`
--   local merlin_exe = vim.fn.exepath "ocamlmerlin"
--   if merlin_exe == "" then
--     return nil
--   end
--
--   -- Get the directory containing `ocamlmerlin`
--   local merlin_dir = vim.fn.fnamemodify(merlin_exe, ":h")
--
--   -- Return the share path relative to the executable
--   return merlin_dir .. "/../share"
-- end
--
-- -- Get the opam share path
-- local opamshare = get_merlin_share_path()
--
-- -- If the share path is found, append it to the runtime path
-- if opamshare then
--   vim.opt.runtimepath:append(opamshare .. "/merlin/vim")
-- end
