build-users-group = nixbld
trusted-users = lyh

experimental-features = nix-command flakes

# The NixOS cache always get priority so we deleted it
# substituters = https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store https://cache.nixos.org/
substituters = https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store 
