accept-flake-config = true
build-users-group = nixbld
experimental-features = nix-command flakes
max-jobs = auto
substituters = https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store?priority=1 https://cache.nixos.org/?priority=2
trusted-users = lyh
